# Generated by Django 5.2.12 on 2026-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='uname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
