# Generated by Django 5.2.12 on 2026-05-03 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_assignment'),
        ('teacher', '0002_teacher_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='classes',
            field=models.ManyToManyField(to='classes.class'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
