# Generated by Django 5.2.12 on 2026-04-19 23:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_membership_class_obj_alter_membership_student'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='bio',
            field=models.TextField(blank=True, help_text='Class description'),
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', through='classes.Membership', to='student.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(blank=True, default='Self-enrolled', max_length=64),
        ),
    ]
