# Generated by Django 5.2.12 on 2026-04-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_options_class_bio_class_created_at_and_more'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='bio',
            field=models.TextField(blank=True, help_text='class description'),
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, through='classes.Membership', to='student.student'),
        ),
    ]
