# Generated by Django 5.2.12 on 2026-05-03 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_assignment_classes_and_more'),
        ('teacher', '0002_teacher_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='classes',
            field=models.ManyToManyField(related_name='assignments', to='classes.class'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teacher.teacher'),
        ),
    ]
